direction: right

N0: "Zero (N0)" {
  style.fill: "#cce5ff"
}
N1: "AddOne\<Zero\> (N1)"
N2: "AddOne\<AddOne\<Zero\>\> (N2)"
N3: "AddOne\<...\> (N3)"
N4: "AddOne\<...\> (N4)"

N0 -> N1: AddOne
N1 -> N2: AddOne
N2 -> N3: AddOne
N3 -> N4: AddOne
